### ISSUE TITLE
[FEAT] 상세 할 일 추가 기능 구현

### ISSUE THREAD

**Issue by hyerin315** [SeSAC-Haul/DoToli-backend#14]
## 목적

사용자가 마감일과 중요도(플래그)를 설정하여 관리할 수 있는 상세 할 일 관리 기능을 백엔드에 구현합니다. 이를 통해 할 일의 세부 상태를 효과적으로 관리할 수 있습니다.

## 작업 내용

**1. Task 엔티티 필드 추가**
- [x] `createdAt` 생성일 필드 추가
- [x] `deadline` 마감일 필드 추가
- [x] `flag` 중요도(플래그) 필드 추가 
- [x] 간단한 할 일 생성 메서드 `createSimpleTask` 구현 
- [x] 상세 할 일 생성 메서드 `createDetailedTask` 구현

**2. TaskService 상세 할일 추가 기능 및 상세 조회 기능 구현**
- [x] 간단한 할 일 `saveSimpleTask`과 상세 할일 `saveDetailedTask`를 구분하여 기능 구현
- [x] 할 일 상세 조회 기능 구현
- [x] 조회, 수정 기능 확장 

**3. TaskController API 구현**
- [x] 간단한 할 일 생성 API로 메소드명 변경
- [x] 상세 할 일 생성 API 추가
- [x] 할 일 상세 조회 API 추가 

## 추가 컨텍스트

이 작업은 기본적인 CRUD 기능을 확장하는 작업이며, 할 일의 상세 기능에 집중합니다.
